version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - grid

  chrome-node:
    image: selenium/node-chrome:latest
    container_name: chrome-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5    # Controls max parallel Chrome sessions
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: "2g"  # Prevents Chrome crashes due to shared memory issues
    networks:
      - grid

  firefox-node:
    image: selenium/node-firefox:latest
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5    # Controls max parallel Firefox sessions
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    shm_size: "2g"  # Prevents Firefox crashes due to shared memory issues
    networks:
      - grid

networks:
  grid:
    driver: bridge